### PR TITLE
Use issue_comment instead of pull_request_review_comment and add trigger workflow_dispatch

### PR DESCRIPTION
**Pull request by robertofrontado**

### CODE REVIEW

**Comment by robertofrontado** [comment]
[TEST]

**Comment by robertofrontado** [comment]
[TEST]

**Comment by robertofrontado** [comment]
[TEST]

**Comment by robertofrontado** [comment]
[TEST]

**Comment by robertofrontado** [comment]
[TEST]

**Comment by robertofrontado** [comment]
[TEST]

**Review by arubio — APPROVED** [review]

**Pull request merged**
